version: '3'
services:

  db:
    image: postgres:10.5-alpine
    hostname: postgres
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: uclh
      POSTGRES_PASSWORD: uclh
      POSTGRES_DB: OMOP-UCLH
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  admin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "50080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  # see below if you need access to the data volume from the host
  # https://forums.docker.com/t/host-path-of-volume/12277/8
  postgres-data: 